//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Approve_Process
    {
        public int ProcessID { get; set; }
        public int ConfigID { get; set; }
        public int GroupNum { get; set; }
        public int RefID { get; set; }
        public Nullable<int> Approver { get; set; }
        public Nullable<System.DateTime> ApproveTime { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Result { get; set; }
        public string CheckOptions { get; set; }
    }
}
