//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Brand : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.Merchant_Brand = new HashSet<Merchant_Brand>();
        }
    
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public int BrandLevel { get; set; }
        public string BrandIcon { get; set; }
        public Nullable<int> BizTypeID { get; set; }
        public Nullable<int> BizCategoryID { get; set; }
        public string ExistingProject { get; set; }
        public Nullable<int> Revenue { get; set; }
        public Nullable<decimal> AreaUsage { get; set; }
        public Nullable<int> FloorBearing { get; set; }
        public Nullable<int> FloorHeight { get; set; }
        public Nullable<int> ElectricityUsage { get; set; }
        public Nullable<int> WaterUsage { get; set; }
        public Nullable<int> DrainUsage { get; set; }
        public Nullable<int> GasUsage { get; set; }
        public Nullable<int> SmokeUsage { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual BizCategory BizCategory { get; set; }
        public virtual BizType BizType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merchant_Brand> Merchant_Brand { get; set; }
    }
}
