//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Campaign_Comment : IStatusFlag,IEditable
    {
        public int CommentID { get; set; }
        public int CampaignID { get; set; }
        public int Overall { get; set; }
        public string CommentContent { get; set; }
        public string CommentAdditional { get; set; }
        public int CommentUserID { get; set; }
        public string CommentUserName { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
