//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Contract : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Contract_Appendix = new HashSet<Contract_Appendix>();
            this.Contract_Brand = new HashSet<Contract_Brand>();
            this.Contract_PaymentTerms = new HashSet<Contract_PaymentTerms>();
            this.Contract_Supplementary = new HashSet<Contract_Supplementary>();
            this.Contract_Unit = new HashSet<Contract_Unit>();
            this.Contract_UnitSpec = new HashSet<Contract_UnitSpec>();
            this.Finance_Accrual = new HashSet<Finance_Accrual>();
            this.Finance_Settlement = new HashSet<Finance_Settlement>();
            this.Merchant_Store = new HashSet<Merchant_Store>();
        }
    
        public int ContractID { get; set; }
        public string ContractCode { get; set; }
        public int ContractType { get; set; }
        public int ContractStatus { get; set; }
        public int ProjectID { get; set; }
        public decimal ContractArea { get; set; }
        public decimal ContractUnitRent { get; set; }
        public decimal ContractMgmtFee { get; set; }
        public int MerchantID { get; set; }
        public string SignerName { get; set; }
        public string SignerIDNumber { get; set; }
        public string SignerPhone { get; set; }
        public int ManageCompanyID { get; set; }
        public string OperatorName { get; set; }
        public string OperatorPhone { get; set; }
        public Nullable<int> ContractLength { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<int> RentFreeLength { get; set; }
        public Nullable<System.DateTime> RentFreeStartDate { get; set; }
        public Nullable<System.DateTime> RentFreeEndDate { get; set; }
        public Nullable<System.DateTime> AccessDate { get; set; }
        public Nullable<int> DecorationLength { get; set; }
        public Nullable<System.DateTime> DecorationStartDate { get; set; }
        public Nullable<System.DateTime> DecorationEndDate { get; set; }
        public Nullable<decimal> DecorationMgmtFee { get; set; }
        public Nullable<decimal> DecorationBond { get; set; }
        public Nullable<int> Condition { get; set; }
        public Nullable<decimal> BidBond { get; set; }
        public Nullable<decimal> ManageBond { get; set; }
        public Nullable<decimal> QualityBond { get; set; }
        public Nullable<int> ParkingLotNum { get; set; }
        public string ParkingLotMemo { get; set; }
        public Nullable<int> AdPointNum { get; set; }
        public string AdPointMemo { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Appendix> Contract_Appendix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Brand> Contract_Brand { get; set; }
        public virtual Merchant Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_PaymentTerms> Contract_PaymentTerms { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Supplementary> Contract_Supplementary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Unit> Contract_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_UnitSpec> Contract_UnitSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finance_Accrual> Finance_Accrual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finance_Settlement> Finance_Settlement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merchant_Store> Merchant_Store { get; set; }
    }
}
