//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Contract_Supplementary : IStatusFlag,IEditable
    {
        public int SupplementaryID { get; set; }
        public int ContractID { get; set; }
        public int SupplementaryType { get; set; }
        public string SignerName { get; set; }
        public string SignerIDNumber { get; set; }
        public string SignerPhone { get; set; }
        public int ManageCompanyID { get; set; }
        public Nullable<decimal> ContractArea { get; set; }
        public Nullable<decimal> ContractUnitRent { get; set; }
        public Nullable<decimal> ContractMgmtFee { get; set; }
        public Nullable<int> MerchantID { get; set; }
        public Nullable<int> ContractLength { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string OperatorName { get; set; }
        public string OperatorPhone { get; set; }
        public string SupplementaryContent { get; set; }
        public System.DateTime SupplementaryStartDate { get; set; }
        public System.DateTime SupplementaryEndDate { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
