//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Dictionary
    {
        public int FieldID { get; set; }
        public string FieldType { get; set; }
        public int FieldValue { get; set; }
        public string FieldName { get; set; }
        public string FieldDesc { get; set; }
        public int Seq { get; set; }
    }
}
