//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Finance_Accrual : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Finance_Accrual()
        {
            this.Finance_SettlementDetail = new HashSet<Finance_SettlementDetail>();
        }
    
        public int AccrualID { get; set; }
        public int MerchantID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public int CompanyID { get; set; }
        public int ItemID { get; set; }
        public int RPFlag { get; set; }
        public int PCFlag { get; set; }
        public int FWFlag { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Finance_Item Finance_Item { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual Merchant_Store Merchant_Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finance_SettlementDetail> Finance_SettlementDetail { get; set; }
    }
}
