//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Finance_Settlement : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Finance_Settlement()
        {
            this.Finance_SettlementDetail = new HashSet<Finance_SettlementDetail>();
        }
    
        public int SettlementID { get; set; }
        public string SettlementCode { get; set; }
        public int SettlementType { get; set; }
        public int MerchantID { get; set; }
        public string MerchantTitle { get; set; }
        public int CompanyID { get; set; }
        public string CompanyTitle { get; set; }
        public Nullable<int> ContractID { get; set; }
        public string UnitName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
        public string SettlementNote { get; set; }
        public decimal ReceivableAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal ConfirmAmount { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public int ConfirmStatus { get; set; }
        public decimal SettlementAmount { get; set; }
        public Nullable<System.DateTime> SettlementTime { get; set; }
        public int SettlementStatus { get; set; }
        public decimal InvoiceAmount { get; set; }
        public Nullable<System.DateTime> InvoiceTime { get; set; }
        public int InvoiceStatus { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string OperatorName { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Merchant Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finance_SettlementDetail> Finance_SettlementDetail { get; set; }
    }
}
