//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Finance_SettlementDetail : IStatusFlag,IEditable
    {
        public int DetailID { get; set; }
        public int SettlementID { get; set; }
        public Nullable<int> AccrualID { get; set; }
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public decimal Price { get; set; }
        public string Unit { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Finance_Accrual Finance_Accrual { get; set; }
        public virtual Finance_Item Finance_Item { get; set; }
        public virtual Finance_Settlement Finance_Settlement { get; set; }
    }
}
