//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class FloorMap_Unit : IStatusFlag
    {
        public int FloorMapUnitID { get; set; }
        public Nullable<int> FloorID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string TextPosition { get; set; }
        public string PathLine { get; set; }
        public string PathQuad1 { get; set; }
        public string PathQuad2 { get; set; }
        public string PathQuad3 { get; set; }
        public string PathQuad4 { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
        public int Status { get; set; }
        public string Comments { get; set; }
    }
}
