//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Intention : IStatusFlag
    {
        public int IntentionID { get; set; }
        public int IntentionType { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ProjectName { get; set; }
        public string Remark { get; set; }
        public System.DateTime InDate { get; set; }
        public int Source { get; set; }
        public int Status { get; set; }
        public Nullable<int> ProcessUserID { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
    }
}
