//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Merchant_Brand : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchant_Brand()
        {
            this.Contract_Brand = new HashSet<Contract_Brand>();
        }
    
        public int MerchantBrandID { get; set; }
        public int MerchantID { get; set; }
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public int BrandType { get; set; }
        public int Authorized { get; set; }
        public Nullable<int> AuthorizedFile { get; set; }
        public Nullable<System.DateTime> AuthorizedSince { get; set; }
        public Nullable<System.DateTime> AuthorizedTo { get; set; }
        public Nullable<System.DateTime> OperationSince { get; set; }
        public Nullable<System.DateTime> OperationTo { get; set; }
        public Nullable<int> Revenue { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Brand> Contract_Brand { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual Merchant_Attachment Merchant_Attachment { get; set; }
    }
}
