//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class News : IStatusFlag,IEditable
    {
        public int NewsID { get; set; }
        public int NewsType { get; set; }
        public int NewsTarget { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContent { get; set; }
        public string NewsBrief { get; set; }
        public string NewsCover { get; set; }
        public int CompanyID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime PublishTime { get; set; }
        public int Status { get; set; }
        public int Stick { get; set; }
        public int InUser { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<int> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string SEO_Title { get; set; }
        public string KeyWords { get; set; }
        public string Description { get; set; }
    }
}
