//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class NHHCG_Project : IStatusFlag
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string BriefName { get; set; }
        public string Feature { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public decimal OperatingArea { get; set; }
        public decimal GrossArea { get; set; }
        public int Population { get; set; }
        public string Position { get; set; }
        public int BusinessType { get; set; }
        public int MonthlyHumanTraffic { get; set; }
        public string PublicTransport { get; set; }
        public string Tel { get; set; }
        public string Introduce { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public string SEO_Title { get; set; }
        public string KeyWords { get; set; }
        public string Description { get; set; }
    }
}
