//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class NHHCG_Complaint : IStatusFlag
    {
        public int ComplaintID { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public int ComplainType { get; set; }
        public int Role { get; set; }
        public string ComplainDetail { get; set; }
        public int Status { get; set; }
        public Nullable<int> Accepter { get; set; }
        public Nullable<System.DateTime> AcceptTime { get; set; }
        public string AcceptResult { get; set; }
        public Nullable<int> InUser { get; set; }
        public System.DateTime InDate { get; set; }
    }
}
