//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Project : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Complaint = new HashSet<Complaint>();
            this.Contract = new HashSet<Contract>();
            this.Project_AdPoint = new HashSet<Project_AdPoint>();
            this.Project_Batch = new HashSet<Project_Batch>();
            this.Project_BizConfig = new HashSet<Project_BizConfig>();
            this.Project_Building = new HashSet<Project_Building>();
            this.Project_Floor = new HashSet<Project_Floor>();
            this.Project_Kiosk = new HashSet<Project_Kiosk>();
            this.Project_Owner = new HashSet<Project_Owner>();
            this.Project_Unit = new HashSet<Project_Unit>();
            this.Repair = new HashSet<Repair>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public string BriefName { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSummary { get; set; }
        public int RegionID { get; set; }
        public int ProvinceID { get; set; }
        public int CityID { get; set; }
        public string AddressLine { get; set; }
        public string AddressInfo { get; set; }
        public string Zipcode { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> GroundArea { get; set; }
        public Nullable<decimal> UndergroundArea { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
        public string RenderingFileName { get; set; }
        public string PlanSummary { get; set; }
        public string PlanHighlight { get; set; }
        public Nullable<int> ParkingLotNum { get; set; }
        public Nullable<int> AdPointNum { get; set; }
        public Nullable<int> MultiBizPositionNum { get; set; }
        public Nullable<System.DateTime> GrandOpeningDate { get; set; }
        public int Stage { get; set; }
        public int ManageCompanyID { get; set; }
        public Nullable<int> BuildingNum { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_AdPoint> Project_AdPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Batch> Project_Batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_BizConfig> Project_BizConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Building> Project_Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Floor> Project_Floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Kiosk> Project_Kiosk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Owner> Project_Owner { get; set; }
        public virtual Province Province { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Unit> Project_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair> Repair { get; set; }
    }
}
