//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Project_UnitAdjust : IStatusFlag,IEditable
    {
        public int AdjustID { get; set; }
        public int AdjustType { get; set; }
        public int UnitID { get; set; }
        public int OriginalUnitID { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Project_Unit Project_Unit { get; set; }
        public virtual Project_Unit Project_Unit1 { get; set; }
    }
}
