//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Project_Floor : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Floor()
        {
            this.Project_AdPoint = new HashSet<Project_AdPoint>();
            this.Project_Kiosk = new HashSet<Project_Kiosk>();
            this.Project_Unit = new HashSet<Project_Unit>();
            this.Repair = new HashSet<Repair>();
        }
    
        public int FloorID { get; set; }
        public int BuildingID { get; set; }
        public int ProjectID { get; set; }
        public string FloorMapFileName { get; set; }
        public int FloorNumber { get; set; }
        public string FloorName { get; set; }
        public string FloorDescription { get; set; }
        public Nullable<decimal> TotalRentArea { get; set; }
        public Nullable<int> TotalRentUnit { get; set; }
        public Nullable<decimal> ContractRentArea { get; set; }
        public Nullable<int> ContractRentUnit { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_AdPoint> Project_AdPoint { get; set; }
        public virtual Project_Building Project_Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Kiosk> Project_Kiosk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Unit> Project_Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair> Repair { get; set; }
    }
}
