//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Project_UnitSpec : IStatusFlag,IEditable
    {
        public int UnitSpecID { get; set; }
        public int UnitID { get; set; }
        public int SpecType { get; set; }
        public string Floor { get; set; }
        public string Ceiling { get; set; }
        public string Wall { get; set; }
        public string Pillar { get; set; }
        public string FloorBearing { get; set; }
        public string WaterSupply { get; set; }
        public string WaterDrain { get; set; }
        public string Door { get; set; }
        public string Logo { get; set; }
        public string ElectricityUsage { get; set; }
        public string FireProtection { get; set; }
        public string Broadcasting { get; set; }
        public string AirCondition { get; set; }
        public string Smoke { get; set; }
        public string Security { get; set; }
        public string Wiring { get; set; }
        public string Water { get; set; }
        public string Gas { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Project_Unit Project_Unit { get; set; }
    }
}
