//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Project_Unit : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project_Unit()
        {
            this.Contract_UnitSpec = new HashSet<Contract_UnitSpec>();
            this.Project_BatchUnit = new HashSet<Project_BatchUnit>();
            this.Project_UnitAdjust = new HashSet<Project_UnitAdjust>();
            this.Project_UnitAdjust1 = new HashSet<Project_UnitAdjust>();
            this.Project_UnitLeasing = new HashSet<Project_UnitLeasing>();
            this.Project_UnitPlan = new HashSet<Project_UnitPlan>();
            this.Project_UnitRequest = new HashSet<Project_UnitRequest>();
            this.Project_UnitSpec = new HashSet<Project_UnitSpec>();
            this.Repair = new HashSet<Repair>();
        }
    
        public int UnitID { get; set; }
        public int ProjectID { get; set; }
        public int BuildingID { get; set; }
        public int FloorID { get; set; }
        public string UnitNumber { get; set; }
        public decimal UnitAera { get; set; }
        public int UnitStatus { get; set; }
        public int UnitType { get; set; }
        public Nullable<int> BizTypeID { get; set; }
        public Nullable<int> BizCategoryID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public int ContractStatus { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string UnitMapFileName { get; set; }
        public string FloorMapLocation { get; set; }
        public string FloorMapDimension { get; set; }
        public string Tag { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual BizCategory BizCategory { get; set; }
        public virtual BizType BizType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_UnitSpec> Contract_UnitSpec { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_BatchUnit> Project_BatchUnit { get; set; }
        public virtual Project_Building Project_Building { get; set; }
        public virtual Project_Floor Project_Floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_UnitAdjust> Project_UnitAdjust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_UnitAdjust> Project_UnitAdjust1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_UnitLeasing> Project_UnitLeasing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_UnitPlan> Project_UnitPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_UnitRequest> Project_UnitRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_UnitSpec> Project_UnitSpec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair> Repair { get; set; }
    }
}
