//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Project_UnitLeasing : IStatusFlag,IEditable
    {
        public int UnitLeasingID { get; set; }
        public int UnitID { get; set; }
        public Nullable<int> LeasingDepartmentID { get; set; }
        public Nullable<int> LeasingPersonID { get; set; }
        public Nullable<System.DateTime> LeasingFinishDate { get; set; }
        public Nullable<int> FireProtectionAuth { get; set; }
        public Nullable<System.DateTime> MeasureReviewDate { get; set; }
        public Nullable<System.DateTime> DesignDate { get; set; }
        public Nullable<System.DateTime> FireProtectionAuthDate { get; set; }
        public Nullable<System.DateTime> AccessDate { get; set; }
        public Nullable<System.DateTime> DecorationStartDate { get; set; }
        public Nullable<System.DateTime> DecorationEndDate { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Project_Unit Project_Unit { get; set; }
    }
}
