//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Sys_Menu : IStatusFlag,IEditable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Menu()
        {
            this.Sys_Role_Menu = new HashSet<Sys_Role_Menu>();
        }
    
        public int MenuID { get; set; }
        public int SeqNo { get; set; }
        public string MenuIcon { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public string MenuDescription { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Sys_Menu Sys_Menu1 { get; set; }
        public virtual Sys_Menu Sys_Menu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Role_Menu> Sys_Role_Menu { get; set; }
    }
}
