//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class Utility_Bill : IStatusFlag,IEditable
    {
        public int BillID { get; set; }
        public int MeterID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal PrevNumber { get; set; }
        public decimal CurNumber { get; set; }
        public decimal UseNumber { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal BillAmount { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public string OperatorName { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public System.DateTime InDate { get; set; }
        public int InUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> EditUser { get; set; }
    
        public virtual Merchant_StoreMeter Merchant_StoreMeter { get; set; }
    }
}
