//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class View_Project_UnitExt
    {
        public int UnitID { get; set; }
        public Nullable<int> BizCategoryID { get; set; }
        public int UnitStatus { get; set; }
        public int UnitType { get; set; }
        public Nullable<int> BizTypeID { get; set; }
        public string BizCategoryName { get; set; }
        public string BizTypeName { get; set; }
        public string UnitTypeName { get; set; }
        public string UnitStatusName { get; set; }
    }
}
