//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class View_Report_Contract
    {
        public string ContractStatusName { get; set; }
        public int ContractID { get; set; }
        public int ContractType { get; set; }
        public int ContractStatus { get; set; }
        public int ProjectID { get; set; }
        public int MerchantID { get; set; }
        public Nullable<int> DecorationLength { get; set; }
        public Nullable<System.DateTime> DecorationEndDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<int> ContractLength { get; set; }
        public Nullable<decimal> QualityBond { get; set; }
        public Nullable<int> AdPointNum { get; set; }
        public Nullable<int> ParkingLotNum { get; set; }
        public int UnitID { get; set; }
        public Nullable<decimal> UnitAvgAera { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public decimal ContractArea { get; set; }
        public decimal ContractUnitRent { get; set; }
        public decimal ContractMgmtFee { get; set; }
        public string ContractCode { get; set; }
    }
}
