//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class View_FloorMap_Unit
    {
        public int UnitID { get; set; }
        public int FloorID { get; set; }
        public string UnitNumber { get; set; }
        public decimal UnitAera { get; set; }
        public Nullable<int> BizTypeID { get; set; }
        public int ContractStatus { get; set; }
        public string ContractStatusName { get; set; }
        public int UnitType { get; set; }
        public string UnitTypeName { get; set; }
        public int ProjectUnitStatus { get; set; }
        public string UnitStatusName { get; set; }
        public string ContractStartDate { get; set; }
        public string ContractEndDate { get; set; }
        public Nullable<decimal> ContractArea { get; set; }
        public Nullable<decimal> ContractUnitRent { get; set; }
        public Nullable<decimal> ContractMgmtFee { get; set; }
        public Nullable<int> DecorationLength { get; set; }
        public Nullable<System.DateTime> DecorationEndDate { get; set; }
        public Nullable<int> ContractLength { get; set; }
        public Nullable<decimal> QualityBond { get; set; }
        public Nullable<int> AdPointNum { get; set; }
        public Nullable<int> ParkingLotNum { get; set; }
        public Nullable<int> FloorMapUnitID { get; set; }
    }
}
