//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHH.Entities
{
    using System;
    using System.Collections.Generic;
    using NHH.Framework;
    using NHH.Framework.Data;
    
    
    public partial class View_Role_Menu
    {
        public int RoleID { get; set; }
        public int MenuID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int SeqNo { get; set; }
        public string MenuIcon { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }
        public string MenuDescription { get; set; }
    }
}
